WITH manifestasi AS (
  INSERT INTO manifestasi_iwa (poin, created_at) VALUES
    ('Menghargai nilai bumi & memakmurkannya sesuai arahan Allah', NOW()),
    ('Menghargai nilai kerja (keterampilan tangan) & melatih Muslim terampil', NOW()),
    ('Meningkatkan kenyamanan, keluarga & sarana hidup; jadikan milik bersama bila perlu', NOW()),
    ('Kesakralan hak menetap; larangan mengusir/mengucilkan dari tempat Iwa''-nya', NOW()),
    ('Korelasi keamanan hidup (ekonomi-sosial) dengan keamanan beragama', NOW()),
    ('Korelasi Iwa'' dengan efektivitas politik & tata kelola pemerintahan', NOW()),
    ('Integrasi negeri-negeri Muslim: kesatuan (al-wahdah) atau persatuan (al-ittihad)', NOW())
  RETURNING id, poin
)
INSERT INTO manifestasi_breakdowns (manifestasi_id, label, keterangan, dalil, contoh)
SELECT m.id, b.label, b.keterangan, b.dalil, b.contoh
FROM (
  VALUES
    ('Menghargai nilai bumi & memakmurkannya sesuai arahan Allah', 'A. Bumi sebagai tempat Iwa'' & ketenangan', 'Iwa'' adalah hak setiap manusia tanpa memandang warna kulit, suku, atau agama. Bumi diciptakan sebagai hamparan (firasy) & buaian (mahd) yang menopang kenyamanan raga-jiwa. Ditegakkan oleh 3 nilai utama: keadilan, tawadhu'', moderat (tawassuth); dirusak oleh 3 kemungkaran: kezaliman, kesombongan, israf.', 'QS ar-Rahman: 10; Hud: 61; al-Baqarah: 22; az-Zukhruf: 10; adz-Dzariyat: 48. Nilai: al-Hadid: 25 (keadilan), al-Furqan: 63 (tawadhu''), al-A''raf: 31 (moderat). Kemungkaran: al-Qashash: 4 & 83; al-Isra'': 37; Luqman: 18; al-Anfal: 73.', 'Tata ruang berkeadilan; pelestarian lingkungan sebagai lawan israf; penolakan atas kesenjangan sosial yang memicu ketidaknyamanan hidup.'),
    ('Menghargai nilai bumi & memakmurkannya sesuai arahan Allah', 'B. Bumi sebagai sumber pencaharian & makanan', 'Dua kaidah: (1) kebebasan menetap untuk beribadah; (2) kebebasan bekerja/berdagang (adh-dharb fi al-ardh). Rezeki bumi terbuka untuk semua-bahkan non-muslim. Dua jalan pengelolaan: manhaj Allah (halal-thayyib) vs manhaj setan (haram-khabits). Wajib menyingkirkan penghalang seperti monopoli & penyewaan tanah oleh yang tak mengelola.', 'QS al-''Ankabut: 56; al-Mulk: 15; al-Baqarah: 126, 168, 267; al-Isra'': 20; Yunus: 59. Hadis: ''tidak ada di luar halal-thayyib selain haram-khabits'' (Bukhari); hadis menanam pohon (Bukhari/Ahmad); ''siapa punya tanah tanamilah atau serahkan'' & larangan sewa tanah (Muslim).', 'Reforma agraria; larangan spekulasi/penelantaran tanah; ekonomi halal & rantai pangan sehat; kritik atas konversi tanah jadi komoditas super mahal.'),
    ('Menghargai nilai bumi & memakmurkannya sesuai arahan Allah', 'C. Hak bersama atas sumber daya umum & larangan monopoli', 'Kekayaan pada dasarnya milik Allah; umat hanya pengelola (mustakhlaf). Harta harus beredar merata, tidak hanya di kalangan kaya. Kanz (menimbun) diancam keras. Sumber daya vital (air, rumput, api) adalah milik bersama-hukumnya menyesuaikan zaman.', 'QS al-Hasyr: 7; al-Baqarah: 188; at-Taubah: 34. Hadis al-Asy''ariyyun (Bukhari-Muslim); ''Muslim berkongsi dalam tiga: air, rumput, api'' (Ahmad); ucapan Umar ttg fudhul harta orang kaya.', 'Zakat produktif & redistribusi; pengelolaan air/energi/hutan sebagai milik publik; kritik atas kapitalisme monopolistik & oligopoli.'),
    ('Menghargai nilai bumi & memakmurkannya sesuai arahan Allah', 'D. Bumi sebagai sumber pengetahuan yang menghantarkan ke Allah', 'Tujuan tertinggi: bumi sebagai laboratorium afaq (alam) & anfus (diri) untuk menyaksikan tanda kekuasaan Allah. Ilmu tanpa bimbingan wahyu menyesatkan (kritik atas Darwin & peradaban modern yang berhenti pada capaian materialistis).', 'QS al-Jatsiyah: 3; adz-Dzariyat: 20; al-''Ankabut: 20; Fathir: 41; az-Zumar: 5; al-Baqarah: 164; ar-Rum: 9; Ghafir: 82-83; al-Hajj: 46; Aal ''Imran: 191.', 'Integrasi sains dengan nilai spiritual; riset yang tak lepas dari etika & keimanan; kritik atas materialisme & saintisme buta.'),
    ('Menghargai nilai kerja (keterampilan tangan) & melatih Muslim terampil', NULL, 'Menumbuhkan cinta kerja-terutama kerja tangan (al-''amal al-yadawi)-sebagai penghidupan terhormat; membenci kemalasan & ketidakberdayaan. Meluruskan makna zuhud: bukan memilih miskin, tetapi mengumpulkan harta halal lalu menyalurkannya untuk kemaslahatan.', 'Hadis: ''Allah mengecam ketidakberdayaan'' (Thabrani); ''sebaik-baik pendapatan adalah hasil kerja tangan'' & ''Allah menyukai mukmin yang al-muhtarif'' (Baihaqi); kisah Anas (laki-laki & kapak, Baihaqi); ucapan Umar (mutawakkilun vs muttakilun); nasihat Mu''adz bin Jabal & Ali bin ''Attam.', 'Pendidikan vokasi & kewirausahaan; etos kerja produktif melawan mental ''menunggu bantuan''; kritik atas kurikulum yang lahirkan sarjana tanpa keterampilan aplikatif & birokrasi gemuk tak produktif.'),
    ('Meningkatkan kenyamanan, keluarga & sarana hidup; jadikan milik bersama bila perlu', NULL, 'Sarana penunjang (rumah, kendaraan, komunikasi) bisa diposisikan sebagai al-milkiyyah al-''ammah saat dibutuhkan. Kelebihan (fadhl) tunggangan/bekal wajib dibagi. Pembangunan properti dibatasi tujuan Iwa'': terpuji bila menaungi yang butuh, tercela bila untuk gengsi & pemisahan kelas.', 'Hadis Abu Sa''id al-Khudri (fadhl zhahr & fadhl zad, Muslim); ''unta & rumah milik setan'' (Abu Daud); hadis membangun masjid (Bukhari-Muslim); QS asy-Syu''ara: 128-131; hadis Tirmidzi & Khabbab (Muslim); tanda kiamat ''penggembala berlomba bangunan tinggi'' (Bukhari-Muslim).', 'Program rumah subsidi & transportasi publik; kritik atas monopoli properti (rumah kosong vs tunawisma); pemerataan akses komunikasi/internet; kritik pembangunan mewah demi prestise.'),
    ('Kesakralan hak menetap; larangan mengusir/mengucilkan dari tempat Iwa''-nya', NULL, 'Mengusir manusia dari rumah/tanahnya karena perbedaan pendapat/kelompok/kepentingan disamakan dengan ''mengusir & membunuh diri sendiri'', karena umat itu satu tubuh. Bahaya terbesar: mengusir pembawa perbaikan (rasul, ulama, cendekiawan)-sunnatullah menetapkan azab bagi pelakunya.', 'QS al-Baqarah: 84-85; al-Isra'': 76-77. Penafsiran ath-Thabari (umat sebagai satu jasad); riwayat Ibn Abbas (pengusiran Nabi -> azab Perang Badar).', 'Penolakan penggusuran paksa & pengungsian akibat konflik; isu hak atas tempat tinggal & refugee; perlindungan tokoh reformis dari pembungkaman/pengasingan.'),
    ('Korelasi keamanan hidup (ekonomi-sosial) dengan keamanan beragama', NULL, 'Ketahanan ekonomi-sosial = sarana; keamanan beragama = tujuan. Jika sarana rusak, tujuan sulit tercapai. Shalat & zakat tak terpisahkan (dimensi ritual + sosial). Umat bertanggung jawab menyediakan ma''wa bagi pelaku penyimpangan agar akar masalahnya terobati.', 'QS Ibrahim: 37; at-Taubah: 11. Hadis Abu Waqid al-Laitsi (Ahmad); ucapan Ibn Zaid & Ibn Mas''ud (''shalat sia-sia tanpa zakat''); hadis sedekah pada pencuri/pezina/orang kaya (Bukhari).', 'Jaring pengaman sosial (bansos, zakat produktif, jaminan kebutuhan pokok); pendekatan atasi kejahatan lewat pemenuhan kebutuhan dasar; kesadaran bahwa kemiskinan ekstrem membuka pintu hilangnya agama.'),
    ('Korelasi Iwa'' dengan efektivitas politik & tata kelola pemerintahan', NULL, 'Iwa'' butuh sarana politik & tata kelola yang menjamin ketahanannya. Di masa awal Islam ia nyaris bergantung pada ketakwaan & ilmu pribadi penguasa-sesuatu yang rapuh karena hanya dimiliki segelintir orang. Karena itu Iwa'' pencaharian & sosial tak boleh bergantung pada preferensi pemimpin, melainkan dilindungi lembaga yang membatasi, mengawasi, dan mengadili wewenang pemerintah, serta legislasi jaminan sosial yang menjaga kehormatan rakyat.', 'Prinsip Umar: maal Allah/maal al-ummah diperlakukan seperti harta anak yatim (riwayat ath-Thabari 4/255 & 4/258); surat Umar kepada Abu Musa al-Asy''ari (''pejabat menyimpang -> rakyat menyimpang''); Umar menolak rumah pribadi di Mesir lalu menjadikannya pasar wakaf; ucapan Ali bin Abu Thalib (kewajiban pada harta orang kaya untuk mencukupi fakir); QS at-Taubah: 31 (bahaya ulama sultan).', 'Lembaga antikorupsi, audit & pengawasan kekuasaan; akuntabilitas & interpelasi pejabat; transparansi keuangan negara; legislasi jaminan sosial (bukan mengandalkan kedermawanan penguasa); kritik atas ''ulama al-muluk wa ar-ru''asa'' yang melegitimasi kezaliman.'),
    ('Integrasi negeri-negeri Muslim: kesatuan (al-wahdah) atau persatuan (al-ittihad)', NULL, 'Tanpa integrasi, Iwa'' & kebangkitan peradaban mustahil, sebab peradaban hanya berdiri di atas hamparan tanah yang luas. Fanatisme (''ashabiyah) kesukuan/ras/kelompok yang memecah dunia Islam menghentikan penyebaran peradaban hingga jumud & runtuh. Negara Islam modern yang justru menguatkan fragmentasi (UU perjalanan, tinggal, kerja) terperangkap kelemahan politik, utang, & kekacauan meski kaya SDM dan SDA.', 'Hadis: ''Bukan golongan kami orang yang kenyang di malam hari sementara tetangganya kelaparan padahal ia tahu'' (Musnad Ahmad)-prinsip kesatuan ekonomi & sumber daya sebagai ciri umat.', 'Blok/integrasi regional yang menyediakan beragam ''Iwa'''' (pemikiran, ekonomi, pencaharian, keamanan) dan menarik talenta-analog Amerika, Eropa, China, Jepang; pasar & mata uang bersama; kritik atas fragmentasi negara Arab/Islam (juga Afrika & Amerika Latin) yang memicu brain drain, arus pengungsi, & kekayaan alam terangkut keluar.')
) AS b(poin, label, keterangan, dalil, contoh)
JOIN manifestasi m ON m.poin = b.poin;
